apiVersion: skaffold/v1beta9
kind: Config
build:
  local: {}
  artifacts:
  - image: hub.docker.com/yaleits/spotapi
    docker:
      dockerfile: k8s/Dockerfile
      buildArgs:
        version: 0.0.0
        prerelease: dev
deploy:
  kubectl:
    manifests:
      - k8s/k8s-*
